apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "cbr0",
          "interface": "eth0",
          "ips": [
              "10.111.1.52"
          ],
          "mac": "22:da:1a:02:94:1e",
          "default": true,
          "dns": {}
      },{
          "name": "default/whereaboutsexample",
          "interface": "net1",
          "mac": "02:c1:9a:00:00:02",
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks: '[{"interface":"net1","mac":"02:c1:9a:00:00:02","name":"whereaboutsexample","namespace":"default"}]'
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "cbr0",
          "interface": "eth0",
          "ips": [
              "10.111.1.52"
          ],
          "mac": "22:da:1a:02:94:1e",
          "default": true,
          "dns": {}
      },{
          "name": "default/whereaboutsexample",
          "interface": "net1",
          "mac": "02:c1:9a:00:00:02",
          "dns": {}
      }]
    kubectl.kubernetes.io/default-container: compute
    kubevirt.io/domain: vm1
    kubevirt.io/migrationTransportUnix: "true"
    linstor.csi.linbit.com/on-storage-lost: remove
    post.hook.backup.velero.io/command: '["/usr/bin/virt-freezer", "--unfreeze", "--name",
      "vm1", "--namespace", "default"]'
    post.hook.backup.velero.io/container: compute
    pre.hook.backup.velero.io/command: '["/usr/bin/virt-freezer", "--freeze", "--name",
      "vm1", "--namespace", "default"]'
    pre.hook.backup.velero.io/container: compute
  creationTimestamp: "2022-04-22T16:28:48Z"
  generateName: virt-launcher-vm1-
  labels:
    kubevirt.io: virt-launcher
    kubevirt.io/created-by: 5a3ac5d5-72ec-4cc9-9628-4efa040381b6
    vm.kubevirt.io/name: vm1
  name: virt-launcher-vm1-p5szm
  namespace: default
  resourceVersion: "90663237"
  uid: 3b01e3b2-9535-43bb-8230-ec1f95cf231c
spec:
  automountServiceAccountToken: false
  containers:
  - command:
    - /usr/bin/virt-launcher-monitor
    - --qemu-timeout
    - 248s
    - --name
    - vm1
    - --uid
    - 5a3ac5d5-72ec-4cc9-9628-4efa040381b6
    - --namespace
    - default
    - --kubevirt-share-dir
    - /var/run/kubevirt
    - --ephemeral-disk-dir
    - /var/run/kubevirt-ephemeral-disks
    - --container-disk-dir
    - /var/run/kubevirt/container-disks
    - --grace-period-seconds
    - "45"
    - --hook-sidecars
    - "0"
    - --ovmf-path
    - /usr/share/OVMF
    env:
    - name: KUBEVIRT_RESOURCE_NAME_red
      value: macvtap.network.kubevirt.io/vxlan42
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: ghcr.io/kvaps/virt-launcher@sha256:9ee9c52629325c8533b21cd615bbf594c37a0e3e02815f6524b6dec0805f72ce
    imagePullPolicy: IfNotPresent
    name: compute
    resources:
      limits:
        devices.kubevirt.io/kvm: "1"
        devices.kubevirt.io/tun: "1"
        devices.kubevirt.io/vhost-net: "1"
        macvtap.network.kubevirt.io/vxlan42: "1"
      requests:
        cpu: 100m
        devices.kubevirt.io/kvm: "1"
        devices.kubevirt.io/tun: "1"
        devices.kubevirt.io/vhost-net: "1"
        ephemeral-storage: 50M
        macvtap.network.kubevirt.io/vxlan42: "1"
        memory: "1204257920"
    securityContext:
      capabilities:
        add:
        - NET_BIND_SERVICE
        - SYS_NICE
        - SYS_PTRACE
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/kubevirt-private
      name: private
    - mountPath: /var/run/kubevirt
      name: public
    - mountPath: /var/run/kubevirt-ephemeral-disks
      name: ephemeral-disks
    - mountPath: /var/run/kubevirt/container-disks
      mountPropagation: HostToContainer
      name: container-disks
    - mountPath: /var/run/kubevirt/hotplug-disks
      mountPropagation: HostToContainer
      name: hotplug-disks
    - mountPath: /var/run/libvirt
      name: libvirt-runtime
    - mountPath: /var/run/kubevirt/sockets
      name: sockets
  - args:
    - --copy-path
    - /var/run/kubevirt-ephemeral-disks/container-disk-data/5a3ac5d5-72ec-4cc9-9628-4efa040381b6/disk_0
    command:
    - /usr/bin/container-disk
    image: kubevirt/fedora-cloud-container-disk-demo:latest
    imagePullPolicy: Always
    name: volumecontainerdisk
    resources:
      limits:
        cpu: 100m
        memory: 40M
      requests:
        cpu: 10m
        ephemeral-storage: 50M
        memory: 1M
    securityContext:
      runAsNonRoot: true
      runAsUser: 107
      seLinuxOptions:
        level: s0
        type: virt_launcher.process
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/kubevirt-ephemeral-disks/container-disk-data/5a3ac5d5-72ec-4cc9-9628-4efa040381b6
      name: container-disks
    - mountPath: /usr/bin
      name: virt-bin-share-dir
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  hostname: vm1
  initContainers:
  - command:
    - /usr/bin/cp
    - /usr/bin/container-disk
    - /init/usr/bin/container-disk
    image: ghcr.io/kvaps/virt-launcher@sha256:9ee9c52629325c8533b21cd615bbf594c37a0e3e02815f6524b6dec0805f72ce
    imagePullPolicy: IfNotPresent
    name: container-disk-binary
    resources:
      limits:
        cpu: 100m
        memory: 40M
      requests:
        cpu: 10m
        memory: 1M
    securityContext:
      privileged: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /init/usr/bin
      name: virt-bin-share-dir
  - args:
    - --no-op
    command:
    - /usr/bin/container-disk
    image: kubevirt/fedora-cloud-container-disk-demo:latest
    imagePullPolicy: Always
    name: volumecontainerdisk-init
    resources:
      limits:
        cpu: 100m
        memory: 40M
      requests:
        cpu: 10m
        ephemeral-storage: 50M
        memory: 1M
    securityContext:
      runAsNonRoot: true
      runAsUser: 107
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/kubevirt-ephemeral-disks/container-disk-data/5a3ac5d5-72ec-4cc9-9628-4efa040381b6
      name: container-disks
    - mountPath: /usr/bin
      name: virt-bin-share-dir
  nodeName: hf-kubevirt-02
  nodeSelector:
    kubevirt.io/schedulable: "true"
  preemptionPolicy: PreemptLowerPriority
  priority: 1000
  priorityClassName: develop
  readinessGates:
  - conditionType: kubevirt.io/virtual-machine-unpaused
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 0
    seLinuxOptions:
      type: virt_launcher.process
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: devices.kubevirt.io/kvm
    operator: Exists
  - effect: NoSchedule
    key: devices.kubevirt.io/tun
    operator: Exists
  - effect: NoSchedule
    key: devices.kubevirt.io/vhost-net
    operator: Exists
  - effect: NoSchedule
    key: macvtap.network.kubevirt.io/vxlan42
    operator: Exists
  volumes:
  - emptyDir: {}
    name: private
  - emptyDir: {}
    name: public
  - emptyDir: {}
    name: sockets
  - emptyDir: {}
    name: virt-bin-share-dir
  - emptyDir: {}
    name: libvirt-runtime
  - emptyDir: {}
    name: ephemeral-disks
  - emptyDir: {}
    name: container-disks
  - emptyDir: {}
    name: hotplug-disks
status:
  conditions:
  - lastProbeTime: "2022-04-22T16:28:48Z"
    lastTransitionTime: "2022-04-22T16:28:48Z"
    message: the virtual machine is not paused
    reason: NotPaused
    status: "True"
    type: kubevirt.io/virtual-machine-unpaused
  - lastProbeTime: null
    lastTransitionTime: "2022-04-22T16:28:51Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-04-22T16:28:53Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-04-22T16:28:53Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-04-22T16:28:48Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://129aa5ec8b7f3657d26ad44a4b6d789d1e59fddefb41af003de26a29609ece1b
    image: sha256:097aa13d2210ab751d5bc45e89a169841a541e45b681fc23f12a95b37a050745
    imageID: ghcr.io/kvaps/virt-launcher@sha256:9ee9c52629325c8533b21cd615bbf594c37a0e3e02815f6524b6dec0805f72ce
    lastState: {}
    name: compute
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-04-22T16:28:51Z"
  - containerID: containerd://3c8572cde0b16869f2495d8659d9fe1e46e60693c96e66827f5921afd3ad77e8
    image: docker.io/kubevirt/fedora-cloud-container-disk-demo:latest
    imageID: docker.io/kubevirt/fedora-cloud-container-disk-demo@sha256:4a0c3f9526551d0294079f1b0171a071a57fe0bf60a2e8529bf4102ee63a67cd
    lastState: {}
    name: volumecontainerdisk
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-04-22T16:28:53Z"
  hostIP: 192.168.242.38
  initContainerStatuses:
  - containerID: containerd://d05df984b3f6cb459dcf2d3fad99356cdd2764ce3c1220f5e0de91ebd2e34350
    image: sha256:097aa13d2210ab751d5bc45e89a169841a541e45b681fc23f12a95b37a050745
    imageID: ghcr.io/kvaps/virt-launcher@sha256:9ee9c52629325c8533b21cd615bbf594c37a0e3e02815f6524b6dec0805f72ce
    lastState: {}
    name: container-disk-binary
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://d05df984b3f6cb459dcf2d3fad99356cdd2764ce3c1220f5e0de91ebd2e34350
        exitCode: 0
        finishedAt: "2022-04-22T16:28:49Z"
        reason: Completed
        startedAt: "2022-04-22T16:28:49Z"
  - containerID: containerd://d2106db2233279b0f091704d5ea3d781f30b6fe989d5f9d02ef88f4cb958b3d8
    image: docker.io/kubevirt/fedora-cloud-container-disk-demo:latest
    imageID: docker.io/kubevirt/fedora-cloud-container-disk-demo@sha256:4a0c3f9526551d0294079f1b0171a071a57fe0bf60a2e8529bf4102ee63a67cd
    lastState: {}
    name: volumecontainerdisk-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://d2106db2233279b0f091704d5ea3d781f30b6fe989d5f9d02ef88f4cb958b3d8
        exitCode: 0
        finishedAt: "2022-04-22T16:28:51Z"
        reason: Completed
        startedAt: "2022-04-22T16:28:51Z"
  phase: Running
  podIP: 10.111.1.52
  podIPs:
  - ip: 10.111.1.52
  qosClass: Burstable
  startTime: "2022-04-22T16:28:48Z"
