// Code generated by MockGen. DO NOT EDIT.
// Source: hotplug.go
//
// Generated by this command:
//
//	mockgen -source hotplug.go -package=container_disk -destination=generated_mock_hotplug.go
//

// Package container_disk is a generated GoMock package.
package container_disk

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
	types "k8s.io/apimachinery/pkg/types"
	v1 "kubevirt.io/api/core/v1"

	disk "kubevirt.io/kubevirt/pkg/os/disk"
)

// MockHotplugMounter is a mock of HotplugMounter interface.
type MockHotplugMounter struct {
	ctrl     *gomock.Controller
	recorder *MockHotplugMounterMockRecorder
	isgomock struct{}
}

// MockHotplugMounterMockRecorder is the mock recorder for MockHotplugMounter.
type MockHotplugMounterMockRecorder struct {
	mock *MockHotplugMounter
}

// NewMockHotplugMounter creates a new mock instance.
func NewMockHotplugMounter(ctrl *gomock.Controller) *MockHotplugMounter {
	mock := &MockHotplugMounter{ctrl: ctrl}
	mock.recorder = &MockHotplugMounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHotplugMounter) EXPECT() *MockHotplugMounterMockRecorder {
	return m.recorder
}

// ComputeChecksums mocks base method.
func (m *MockHotplugMounter) ComputeChecksums(vmi *v1.VirtualMachineInstance, sourceUID types.UID) (*DiskChecksums, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeChecksums", vmi, sourceUID)
	ret0, _ := ret[0].(*DiskChecksums)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComputeChecksums indicates an expected call of ComputeChecksums.
func (mr *MockHotplugMounterMockRecorder) ComputeChecksums(vmi, sourceUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeChecksums", reflect.TypeOf((*MockHotplugMounter)(nil).ComputeChecksums), vmi, sourceUID)
}

// ContainerDisksReady mocks base method.
func (m *MockHotplugMounter) ContainerDisksReady(vmi *v1.VirtualMachineInstance, notInitializedSince time.Time, sourceUID types.UID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerDisksReady", vmi, notInitializedSince, sourceUID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerDisksReady indicates an expected call of ContainerDisksReady.
func (mr *MockHotplugMounterMockRecorder) ContainerDisksReady(vmi, notInitializedSince, sourceUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerDisksReady", reflect.TypeOf((*MockHotplugMounter)(nil).ContainerDisksReady), vmi, notInitializedSince, sourceUID)
}

// IsMounted mocks base method.
func (m *MockHotplugMounter) IsMounted(vmi *v1.VirtualMachineInstance, volumeName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMounted", vmi, volumeName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMounted indicates an expected call of IsMounted.
func (mr *MockHotplugMounterMockRecorder) IsMounted(vmi, volumeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMounted", reflect.TypeOf((*MockHotplugMounter)(nil).IsMounted), vmi, volumeName)
}

// MoundAndVerifyFromPod mocks base method.
func (m *MockHotplugMounter) MoundAndVerifyFromPod(vmi *v1.VirtualMachineInstance, sourceUID types.UID) (map[string]*disk.DiskInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoundAndVerifyFromPod", vmi, sourceUID)
	ret0, _ := ret[0].(map[string]*disk.DiskInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoundAndVerifyFromPod indicates an expected call of MoundAndVerifyFromPod.
func (mr *MockHotplugMounterMockRecorder) MoundAndVerifyFromPod(vmi, sourceUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoundAndVerifyFromPod", reflect.TypeOf((*MockHotplugMounter)(nil).MoundAndVerifyFromPod), vmi, sourceUID)
}

// MountAndVerify mocks base method.
func (m *MockHotplugMounter) MountAndVerify(vmi *v1.VirtualMachineInstance) (map[string]*disk.DiskInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MountAndVerify", vmi)
	ret0, _ := ret[0].(map[string]*disk.DiskInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MountAndVerify indicates an expected call of MountAndVerify.
func (mr *MockHotplugMounterMockRecorder) MountAndVerify(vmi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MountAndVerify", reflect.TypeOf((*MockHotplugMounter)(nil).MountAndVerify), vmi)
}

// Umount mocks base method.
func (m *MockHotplugMounter) Umount(vmi *v1.VirtualMachineInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Umount", vmi)
	ret0, _ := ret[0].(error)
	return ret0
}

// Umount indicates an expected call of Umount.
func (mr *MockHotplugMounterMockRecorder) Umount(vmi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Umount", reflect.TypeOf((*MockHotplugMounter)(nil).Umount), vmi)
}

// UmountAll mocks base method.
func (m *MockHotplugMounter) UmountAll(vmi *v1.VirtualMachineInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UmountAll", vmi)
	ret0, _ := ret[0].(error)
	return ret0
}

// UmountAll indicates an expected call of UmountAll.
func (mr *MockHotplugMounterMockRecorder) UmountAll(vmi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UmountAll", reflect.TypeOf((*MockHotplugMounter)(nil).UmountAll), vmi)
}
